version: '3.4'
services:
  api01:
    image: node:14-alpine
    container_name: api02
    logging:
      driver: syslog
    restart: on-failure
    volumes:
      - ${PWD}/api02:/home/    
    networks:
      - production
