version: '3.4'
services:
  api01:
    image: nodejs:latest
    container_name: api01
    logging:
      driver: syslog
    restart: on-failure
    volumes:
      - ${PWD}/api01:/home/    
    networks:
      - production
networks:
  production:
    name: producao
    driver: bridge 
